# Netlify configuration for Base Ninja Game

[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"
  NPM_FLAGS = "--legacy-peer-deps"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"

# Production context
[context.production]
  environment = { NODE_VERSION = "20" }

# Deploy preview context  
[context.deploy-preview]
  environment = { NODE_VERSION = "20" }

# Branch deploy context
[context.branch-deploy]
  environment = { NODE_VERSION = "20" }
